<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class GagBase extends MagratheaModel implements iMagratheaModel {

	public $id, $content, $author, $location, $hash, $origin, $date, $used_in;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "gags";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["content"] = "text";
		$this->dbValues["author"] = "string";
		$this->dbValues["location"] = "string";
		$this->dbValues["hash"] = "string";
		$this->dbValues["origin"] = "string";
		$this->dbValues["date"] = "datetime";
		$this->dbValues["used_in"] = "string";

		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

	}

	// >>> relations:

}

class GagControlBase extends MagratheaModelControl {
	protected static $modelName = "Gag";
	protected static $dbTable = "gags";
}
?>