version: '3.7'

services:
  # dunedin_app:
  #   container_name: "dunedin-app"
  #   hostname: dunedin.localhost.com
  #   build:
  #     context: .
  #     dockerfile: app/Dockerfile
  #   env_file: docker/.env
  #   ports:
  #     - 80:4200
  #   volumes:
  #     - ./app:/home/node/app

  # dunedin_mongodb:
  #   container_name: "dunedin-mongo"
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-mongo
  #   env_file: docker/.env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
  #     MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./docker/database:/application

  # dunedin_api:
  #   container_name: "dunedin-api"
  #   hostname: dunedin.localhost.com
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-api
  #   env_file: docker/.env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./api:/home/node/api
  #     - ./api/node_modules:/home/node/api/node_modules


  dunedin_mysql:
    image: mariadb
    container_name: "dunedin-mysql"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dunedin
      - MYSQL_USER=dunedin
      - MYSQL_PASSWORD=dunedin
    ports:
      - "3306:3306"

  dunedin_php:
    hostname: dunedin-api.localhost.com
    container_name: "dunedin-php"
    build:
      context: .
      dockerfile: ./docker/Dockerfile-apache
    volumes: 
      - ./api-php:/var/www
#      - ./_magrathea:/var/www/magrathea
      - /Users/paulohenriquemartins/Paulo/MagratheaPHP/Magrathea:/var/www/magrathea
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      LETS_ENCRYPT_EMAIL: "dunedin@platypusweb.com.br"
      LETS_ENCRYPT_DOMAINS: "dunedin-api.localhost.com,www.dunedin-api.localhost.com"

  dunedin_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dunedin-dev_pma
    environment:
      PMA_HOST: dunedin_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - dunedin_mysql
    ports:
      - 8183:80



