version: '3.7'

services:
  dunedin_mongodb:
    container_name: "dunedin-mongo"
    build:
      context: .
      dockerfile: docker/Dockerfile-mongo
    env_file: docker/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./docker/database:/application

  dunedin_api:
    container_name: "dunedin-api"
    hostname: dunedin.localhost.com
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    env_file: docker/.env
    ports:
      - "3000:3000"
    volumes:
      - ./api:/home/node/api
      - ./api/node_modules:/home/node/api/node_modules
